/**
 * Range Size Analysis Module
 *
 * Core functions for analyzing optimal Uniswap v3 range sizes.
 * Used by the range-size analysis script for backtesting.
 */

export interface PricePoint {
  timestamp: number;
  price: number;
  volumeUsd?: number; // Volume in USD for this point (if available)
}

export interface RangeAnalysis {
  rangeWidth: number; // Total width as decimal (e.g., 0.20 = 20%)
  rangeWidthPercent: number; // Display percentage (e.g., 20)
  outOfRangeCount: number;
  outOfRangePercent: number;
  expectedAdjustmentsPerMonth: number;
  estimatedFeeYieldAPY: number;
  estimatedGasCostAPY: number;
  netAPY: number;
  actualFeeIncomeUsd: number; // Actual fee income in USD for the analyzed period
  daysAnalyzed: number; // Number of days analyzed
}

/**
 * Check if price is out of range
 */
export function isOutOfRange(price: number, centerPrice: number, rangeWidth: number): boolean {
  const halfWidth = rangeWidth / 2;
  const lowerBound = centerPrice * (1 - halfWidth);
  const upperBound = centerPrice * (1 + halfWidth);
  return price < lowerBound || price > upperBound;
}

/**
 * Calculate distance to nearest range edge (as fraction of range width)
 */
export function distanceToEdge(price: number, centerPrice: number, rangeWidth: number): number {
  const halfWidth = rangeWidth / 2;
  const lowerBound = centerPrice * (1 - halfWidth);
  const upperBound = centerPrice * (1 + halfWidth);
  const rangeSize = upperBound - lowerBound;

  if (price < lowerBound) {
    return (lowerBound - price) / rangeSize;
  }
  if (price > upperBound) {
    return (price - upperBound) / rangeSize;
  }

  const distToLower = (price - lowerBound) / rangeSize;
  const distToUpper = (upperBound - price) / rangeSize;
  return Math.min(distToLower, distToUpper);
}

/**
 * Calculate actual fee yield from historical swap data
 * Uses real volume data from swap events
 */
export function calculateActualFeeYield(
  rangeWidth: number,
  poolFeeBps: number,
  pricePoints: PricePoint[],
  positionSizeUsd: number,
  initialPrice: number
): number {
  if (pricePoints.length === 0) {
    return 0;
  }

  // Calculate total volume from swaps
  const totalVolumeUsd = pricePoints.reduce((sum, point) => sum + (point.volumeUsd || 0), 0);

  // Calculate days analyzed
  const daysAnalyzed =
    pricePoints.length > 0
      ? (pricePoints[pricePoints.length - 1].timestamp - pricePoints[0].timestamp) / 86400
      : 1;

  if (daysAnalyzed === 0) {
    return 0;
  }

  // Annualize volume
  const annualVolumeUsd = (totalVolumeUsd / daysAnalyzed) * 365;

  // Fee rate (e.g., 0.05% = 500 bps / 10000)
  const feeRate = poolFeeBps / 10000;

  // Total fees generated by pool
  const totalFeesUsd = annualVolumeUsd * feeRate;

  // Estimate position's share of fees
  // This is simplified - in reality depends on:
  // 1. Position liquidity vs total pool liquidity
  // 2. How much volume occurs within the position's price range
  // 3. Capital efficiency (tighter ranges = more fees per dollar)

  // Simplified model: assume position captures fees proportional to:
  // - Its capital efficiency (1/rangeWidth)
  // - Its share of total liquidity (positionSize / estimatedTotalLiquidity)

  // Rough estimate: assume total liquidity is ~10x the daily volume
  const dailyVolumeUsd = annualVolumeUsd / 365;
  const estimatedTotalLiquidityUsd = dailyVolumeUsd * 10; // Assume liquidity is 10x daily volume
  const liquidityShare = Math.min(positionSizeUsd / estimatedTotalLiquidityUsd, 1.0);

  // Capital efficiency factor (tighter ranges capture more fees per dollar)
  // A ±5% range (0.1 width) is 2x more efficient than ±10% range (0.2 width)
  const capitalEfficiencyFactor = 1 / rangeWidth;

  // Base fee share = liquidity share * capital efficiency
  // But we need to scale this appropriately - tighter ranges should get proportionally more
  // Cap the fee share at a reasonable maximum (e.g., 5% of total fees for very tight ranges)
  const baseFeeShare = liquidityShare * capitalEfficiencyFactor;
  const maxFeeShare = 0.05; // Cap at 5% of total fees
  const feeShare = Math.min(baseFeeShare / 100, maxFeeShare); // Divide by 100 to scale down

  // Calculate annual fee yield
  const annualFeeYield = totalFeesUsd * feeShare;

  return (annualFeeYield / positionSizeUsd) * 100; // Return as APY percentage
}

/**
 * Estimate fee yield based on range width and pool characteristics
 * Simplified model: fee yield is inversely proportional to range width
 * @deprecated Use calculateActualFeeYield with real swap data instead
 */
export function estimateFeeYield(
  rangeWidth: number,
  poolFeeBps: number,
  dailyVolumeUsd: number,
  positionSizeUsd: number
): number {
  // Base fee rate (e.g., 0.05% = 500 bps)
  const feeRate = poolFeeBps / 10000;

  // Annual trading volume
  const annualVolume = dailyVolumeUsd * 365;

  // Fee income = volume * fee rate
  const totalFeeIncome = annualVolume * feeRate;

  // Simplified: assume liquidity is proportional to range width
  // Tighter ranges = more capital efficiency = higher yield
  // This is a simplification - actual liquidity distribution is more complex
  const capitalEfficiencyFactor = 1 / rangeWidth; // Inverse relationship

  // Estimate position's share of fees based on capital efficiency
  // In reality, this depends on actual liquidity distribution
  const estimatedShare = (positionSizeUsd / (annualVolume * 0.1)) * capitalEfficiencyFactor; // Rough estimate
  const annualFeeYield = totalFeeIncome * Math.min(estimatedShare, 0.1); // Cap at 10% of total fees

  return (annualFeeYield / positionSizeUsd) * 100; // Return as APY percentage
}

/**
 * Estimate gas costs for range adjustments
 */
export function estimateGasCosts(
  adjustmentsPerMonth: number,
  gasPriceGwei: number = 0.1, // Arbitrum typical gas price
  gasPerAdjustment: number = 350000, // Close + open position
  ethPriceUsd: number = 3000 // ETH price in USD
): number {
  const gasCostEth = (adjustmentsPerMonth * gasPerAdjustment * gasPriceGwei) / 1e9;
  return gasCostEth * ethPriceUsd * 12; // Annual cost in USD
}

/**
 * Analyze a specific range width
 */
export function analyzeRangeWidth(
  rangeWidth: number,
  pricePoints: PricePoint[],
  initialPrice: number,
  poolFeeBps: number,
  dailyVolumeUsd: number,
  positionSizeUsd: number,
  minAdjustmentInterval: number = 3600 // 1 hour minimum
): RangeAnalysis {
  let outOfRangeCount = 0;
  let adjustmentCount = 0;
  let lastAdjustmentTime = 0;

  for (const point of pricePoints) {
    if (isOutOfRange(point.price, initialPrice, rangeWidth)) {
      outOfRangeCount++;
      // Count as adjustment if enough time has passed
      if (point.timestamp - lastAdjustmentTime >= minAdjustmentInterval) {
        adjustmentCount++;
        lastAdjustmentTime = point.timestamp;
      }
    }
  }

  const totalPoints = pricePoints.length;
  const outOfRangePercent = totalPoints > 0 ? (outOfRangeCount / totalPoints) * 100 : 0;
  const daysAnalyzed =
    totalPoints > 0
      ? (pricePoints[pricePoints.length - 1].timestamp - pricePoints[0].timestamp) / 86400
      : 0;
  const adjustmentsPerMonth = daysAnalyzed > 0 ? (adjustmentCount / daysAnalyzed) * 30 : 0;

  // Use actual fee yield if volume data is available, otherwise fall back to estimate
  const hasVolumeData = pricePoints.some((p) => p.volumeUsd !== undefined && p.volumeUsd > 0);
  const feeYieldAPY = hasVolumeData
    ? calculateActualFeeYield(rangeWidth, poolFeeBps, pricePoints, positionSizeUsd, initialPrice)
    : estimateFeeYield(rangeWidth, poolFeeBps, dailyVolumeUsd, positionSizeUsd);

  // Calculate actual fee income for the analyzed period (not annualized)
  let actualFeeIncomeUsd = 0;
  if (hasVolumeData && daysAnalyzed > 0) {
    // Calculate total volume and fees for the period
    const totalVolumeUsd = pricePoints.reduce((sum, point) => sum + (point.volumeUsd || 0), 0);
    const feeRate = poolFeeBps / 10000;
    const totalFeesUsd = totalVolumeUsd * feeRate;

    // Estimate position's share (same logic as calculateActualFeeYield)
    const dailyVolumeUsd = totalVolumeUsd / daysAnalyzed;
    const estimatedTotalLiquidityUsd = dailyVolumeUsd * 10;
    const liquidityShare = Math.min(positionSizeUsd / estimatedTotalLiquidityUsd, 1.0);
    const capitalEfficiencyFactor = 1 / rangeWidth;
    const baseFeeShare = liquidityShare * capitalEfficiencyFactor;
    const maxFeeShare = 0.05;
    const feeShare = Math.min(baseFeeShare / 100, maxFeeShare);

    // Actual fee income for this period
    actualFeeIncomeUsd = totalFeesUsd * feeShare;
  }

  const gasCostUsd = estimateGasCosts(adjustmentsPerMonth);
  const gasCostAPY = (gasCostUsd / positionSizeUsd) * 100;
  const netAPY = feeYieldAPY - gasCostAPY;

  return {
    rangeWidth,
    rangeWidthPercent: rangeWidth * 100,
    outOfRangeCount,
    outOfRangePercent,
    expectedAdjustmentsPerMonth: adjustmentsPerMonth,
    estimatedFeeYieldAPY: feeYieldAPY,
    estimatedGasCostAPY: gasCostAPY,
    netAPY,
    actualFeeIncomeUsd,
    daysAnalyzed,
  };
}

/**
 * Simulate price movements using geometric Brownian motion
 * This is a simplified model - in production, use actual historical data
 */
export function simulatePriceMovements(
  initialPrice: number,
  volatility: number, // Annual volatility (e.g., 0.8 for 80%)
  days: number,
  stepsPerDay: number = 24, // Hourly steps
  randomFn: () => number = Math.random // Allow injection for testing
): PricePoint[] {
  const dt = 1 / (365 * stepsPerDay); // Time step in years
  const sqrtDt = Math.sqrt(dt);
  const prices: PricePoint[] = [];
  let currentPrice = initialPrice;
  const startTime = Math.floor(Date.now() / 1000) - days * 24 * 3600;

  for (let step = 0; step < days * stepsPerDay; step++) {
    // Geometric Brownian Motion: dS = S * (mu * dt + sigma * dW)
    // For simplicity, assume drift = 0 (random walk)
    const randomShock = (randomFn() - 0.5) * 2; // -1 to 1
    const priceChange = currentPrice * volatility * sqrtDt * randomShock;
    currentPrice = Math.max(currentPrice + priceChange, initialPrice * 0.1); // Floor at 10% of initial

    prices.push({
      timestamp: startTime + step * 3600,
      price: currentPrice,
    });
  }

  return prices;
}
